### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tsuyori-S** [tsuyori-S/furima-37747#24]
# URL
https://furima-37747.herokuapp.com/

# Basic認証IDとパスワード
ID: admin
password: 2222

# 出品者用のメールアドレスとパスワード
email: 111@111
password: 1a1a1a

# 購入者用のメールアドレスとパスワード
email: 222@222
password: 2b2b2b

**Comment by soll02solglas** [comment]
@tsuyori-S さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

![lgtm_01](https://user-images.githubusercontent.com/30042165/166416883-d5fc60b5-2701-41bb-8e5f-7b19bdf644a5.png)

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**
